attack_variant: autoprompt

# Attack hyperparameters (consistent with GCG's)
attack_n_iter: 1000
evaluate_flips_on_strs: False  # OFF for AutoPrompt / Corpus-Poisoning (as they solely optimize input-ids)
avg_grad_batch_size: 1
k_candidates: 256
beam_search_config:
  perform: False

# Unused for this variant:
n_flips_to_gen: 256

# Failed components:
perform_arca_opt: False
n_sim_tokens_flips_to_gen: 0  # POSITIVE -> # of sim-based candidates to add, NEGATIVE -> # of sim-based candidates per-token to consider when filtering the EXISTING grad-based candidates
use_rephraser: False




