
# Attack init:
mal_info: random_toxic_text
adv_passage_init:  lm_gen # 'golden_passages', 'dummy_token', 'att_queries', ..

# Trigger constraints (defines the set of optimized tokens)
trigger_loc: suffix
trigger_len: 100

# Fluency constraints (defines the objective in the loss):
flu_alpha: 0 # weight for fluency score
l2_alpha: 0 # weight for l2 penalty term
fluency_model_name: gpt2  #bert_mlm  # gpt2

