# Crafts a 150-tokens trigger, with no guarantees.

# Attack init:
mal_info: random_toxic_text
adv_passage_init:  'lm_gen' # 'golden_passages', 'dummy_token', 'att_queries', ..

# Trigger constraints (defines the set of optimized tokens)
trigger_loc: trigger_only # 'override_prefix', 'override_suffix', 'append_suffix_dummy', 'append_suffix_gen'
trigger_len: 100

# Fluency constraints (defines the objective in the loss):
flu_alpha: 0 # weight for masked-language-model fluency score
l2_alpha: 0 # weight for l2 penalty term
fluency_model_name: gpt2  # gpt2

