# In case we attack an held-out set (e.g., covering):
query_choice: cluster
target_choice: predefined_centroid
cluster_idx: 0  # idx to attack
adv_loss_name: sum_of_sim  # 'sum_of_sim' (simply the sum of similarities), 'sum_of_high_margin'