# Attack objective (defines the core-objective to optimize)
query_choice: cluster  # 'naive', 'cluster'
target_choice: queries  # accumulates grad of all queries; for ablation, DOES NOT WORK WITH GRAD-AVG!
cluster_idx: 34  # idx to attack
adv_loss_name: sum_of_sim  # 'sum_of_sim' (simply the sum of similarities), 'sum_of_high_margin'

