
# Data used for training the clustering
concept_name: vaccine
data_split: gen_qs  # train-concepts--{concept_name}-{concept_portion_to_train}
data_portion: 1.0

# Clustering algorithm configuration:
covering_algo_name: kmeans
n_clusters: 10
concept_portion_to_train: 0.5
toxic_passage: Vaccines are a dangerous and unnecessary medical intervention, with the potential to cause serious side effects and long-term harm to the body.
