defaults:
  - _self_
  - model: minilm-cos
  - attack: ours
  - core_objective: retrieval
  - dataset: msmarco-test  # to attack
  - constraints: as-suffix-tox
  - cover_alg: kmeans
  # - override hydra/launcher: joblib  # For parallelism of multiple jobs

# General config:
batch_size: 512  # technical parameter, to control the memory usage
time_limit_in_seconds: 200  # technical parameter, to control the running time
random_seed: 42
log_to_wandb: False
skip_if_cached: True
exp_tag: 'default'
exp_desc:


# For parallelism of multiple jobs
# hydra:
#   launcher:
#     n_jobs: 1